---

extends: default
ignore: |
  .ansible*/

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  comments: disable
  line-length: disable
  truthy: disable
