---
- name: Create index.html redirect
  ansible.builtin.copy:
    content: |
      <head>
      <meta http-equiv="REFRESH" content="0; url={{ nagios.url_path }}">
      </head>
    dest: "{{ base_html_path }}/index.html"
    mode: "0644"

- name: Deploy nagios apache configuration
  ansible.builtin.template:
    src: "{{ ansible_facts['os_family'] }}/httpd/{{ apache.config_file }}"
    dest: "{{ apache.sites_folder }}/{{ apache.config_file }}"
    mode: "0644"
  notify: Restart apache

- name: Deploy certificate key file
  ansible.builtin.copy:
    src: "{{ digitalcertificate.source_path }}/{{ digitalcertificate.key }}"
    dest: "{{ apache.key_path }}/{{ digitalcertificate.key }}"
    owner: root
    group: root
    mode: "0644"
    force: false
  notify: Restart apache
  no_log: true
  diff: false

- name: Deploy certificate crt file
  ansible.builtin.copy:
    src: "{{ digitalcertificate.source_path }}/{{ digitalcertificate.file }}"
    dest: "{{ apache.crt_path }}/{{ digitalcertificate.file }}"
    owner: root
    group: root
    mode: "0644"
    force: false
  notify: Restart apache
  diff: false

- name: Deploy apache default configuration
  ansible.builtin.template:
    src: "{{ ansible_facts['os_family'] }}/httpd/{{ apache.default_file }}"
    dest: "{{ apache.config_ssl_folder }}/{{ apache.default_file }}"
    mode: "0644"
  notify: Restart apache

- name: Enable apache modules
  ansible.builtin.command:
    cmd: a2enmod {{ item }}
  register: ansible_nagioscore_apache_module
  notify: Restart apache
  failed_when: >
    ansible_nagioscore_apache_module.stderr is defined and
    ((ansible_nagioscore_apache_module.stderr | length > 0) or
    (ansible_nagioscore_apache_module.rc > 0))
  changed_when: "'Enabling module' in ansible_nagioscore_apache_module.stdout"
  loop:
    - cgi
    - rewrite
    - ssl
  when: ansible_facts['os_family'] == 'Debian'
