---
- name: Configure apache ssl
  ansible.builtin.template:
    src: "{{ ansible_facts['os_family'] }}/httpd/{{ apache.config_ssl_file }}"
    dest: "{{ apache.config_ssl_folder }}/{{ apache.config_ssl_file }}"
    mode: "0644"
  notify: Restart apache
