---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install postfix package
  ansible.builtin.apt:
    name:
      - postfix
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install apache and openssl packages
  ansible.builtin.apt:
    name:
      - apache2
      - apache2-utils
      - openssl
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install nagios core packages
  ansible.builtin.apt:
    name:
      - nagios4
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install nagios plugins
  ansible.builtin.apt:
    name: "{{ nrpe_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install essential packages
  ansible.builtin.apt:
    name: "{{ essential_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install rrdtool packages
  ansible.builtin.apt:
    name: "{{ rrdtool_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add apache user to nagios group
  ansible.builtin.user:
    name: "{{ apache.user }}"
    groups: "{{ nagios.group }}"
    append: true
