---

- name: include vars for {{ item }}
  include_vars: "inventory/nagios_hosts/{{ item }}.yml"
  when: _nagios_hosts is defined

- name: create host definition {{ _host.name }}
  template:
    src: "nagios/etc/assets/host_definition.cfg"
    dest: "{{ tempfolder.path }}/config/assets/{{ _host.name }}.cfg"
    mode: 0644
