---

- name: "include vars for {{ _nagios_host_file|basename }}"
  include_vars: "{{ _nagios_host_file }}"

- name: "create host definition {{ _host.host_name }}"
  template:
    src: "nagios/etc/assets/host_definition.cfg"
    dest: "{{ tempfolder.path }}/assets/{{ _host.host_name }}.cfg"
    mode: 0664
