---
- name: Set OS dependent tasks
  ansible.builtin.include_tasks:
    file: "{{ lookup('ansible.builtin.first_found', ansible_nagioscore_os_task_files) }}"
  vars:
    ansible_nagioscore_os_task_files:
      files:
        - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yaml"
        - "{{ ansible_facts['distribution'] }}.yaml"
        - "{{ ansible_facts['os_family'] }}_{{ ansible_facts['distribution_major_version'] }}.yaml"
        - "{{ ansible_facts['os_family'] }}.yaml"
      paths:
        - "{{ role_path }}/tasks"
