---

- name: set timezone
  timezone:
    name: "{{ time_zone }}"

- name: set OS dependent variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yaml'
    - '{{ ansible_facts.distribution }}.yaml'
    - '{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yaml'
    - '{{ ansible_facts.os_family }}.yaml'
  tags:
    - nagios-apache-config
    - nagios-config
    - nagios-nrdp
    - nagios-nrdp-config

- name: set OS dependent tasks
  include_tasks: '{{ item }}'
  with_first_found:
    - '{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yaml'
    - '{{ ansible_facts.distribution }}.yaml'
    - '{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yaml'
    - '{{ ansible_facts.os_family }}.yaml'

- include_tasks: network.yaml

- include_tasks: postfix.yaml

- include_tasks: nagios_apache.yaml
  tags:
    - nagios-apache-config

- include_tasks: nagios.yaml

- include_tasks: nagios_nrdp.yaml
  when: install_nrdp
  tags:
    - nagios-nrdp

- include_tasks: pnp4nagios.yaml
  when: install_pnp4nagios

- include_tasks: nagios_config.yaml
  tags:
    - nagios-config
