---
- name: start nagios
  service:
    name: '{{ nagios.service_name }}'
    state: started
    enabled: yes

- name: add users to htpasswd file
  include_tasks: "nagios_httpasswd.yaml"
  with_items: "{{ nagios_contacts }}"
  loop_control:
    loop_var: _contact
  no_log: true

- name: create folder
  file:
    state: directory
    path: "{{ nagios.var_spool_path }}/checkresults"
    owner: "{{ nagios.user }}"
    group: "{{ nagios.group }}"
    mode: '0750'

- name: create resource config
  template:
    src: nagios/etc/resource.cfg
    dest: "{{ nagios.etc_path }}/resource.cfg"
    owner: "{{ nagios.user }}"
    group: "{{ nagios.group }}"
    mode: 0664

- name: create nagios config
  template:
    src: nagios/etc/{{ item }}
    dest: "{{ nagios.etc_path }}/{{ item }}"
    backup: yes
    mode: 0664
  notify: reload nagios
  with_items:
    - nagios.cfg
    - cgi.cfg

- name: assets folder creation
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nagios.user }}"
    group: "{{ nagios.group }}"
    mode: 0750
  with_items: "{{ __nagios_config_parameters.cfg_dir }}"

- name: Download check_ncpa.py
  get_url:
    url: https://raw.githubusercontent.com/NagiosEnterprises/ncpa/master/client/check_ncpa.py
    dest: /usr/lib/nagios/plugins/check_ncpa.py
    mode: '0755'
