---

- name: update user to htpasswd file {{ _contact }}
  htpasswd:
    path: "{{ nagios.passwd_file }}"
    name: "{{ _contact }}"
    password: "{{ nagios_contacts[_contact]['password'] }}"
    state: "{{ nagios_contacts[_contact]['state'] | default('present') }}"
    owner: root
    group: "{{ nagios_apache.group }}"
    mode: 0640
  no_log: true
  when: nagios_contacts[_contact]['password'] is defined
