---
#https://github.com/NagiosEnterprises/nrdp

- name: check if nrdp folder exists
  stat:
    path: /usr/local/nrdp
  register: nrdppath
  tags:
    - nagios-nrdp

- name: create temporary directory
  tempfile:
    state: directory
    suffix: nrdp
  register: tempfolder
  changed_when: false
  when: not nrdppath.stat.exists or nrdp_force_reinstall
  tags:
    - nagios-nrdp

- name: creates temp nrdp
  unarchive:
    src: "https://github.com/NagiosEnterprises/nrdp/archive/{{ nrdp_version }}.tar.gz"
    dest: "{{ tempfolder.path }}"
    remote_src: yes
    creates: "{{ tempfolder.path }}/nrdp-{{ nrdp_version }}"
  changed_when: false
  when: not nrdppath.stat.exists or nrdp_force_reinstall
  tags:
    - nagios-nrdp

- name: nrdp folder creation
  file:
    path: /usr/local/nrdp
    state: directory
    owner: "{{ nagios.user }}"
    group: "{{ nagios.group }}"
    mode: 0755
  tags:
    - nagios-nrdp

- name: files synchronization to nrp folder
  synchronize:
    src: "{{ tempfolder.path }}/nrdp-{{ nrdp_version }}/{{ item }}"
    dest: "/usr/local/nrdp"
    perms: yes
  delegate_to: "{{ inventory_hostname }}"
  with_items:
    - clients
    - server
    - LICENSE.md
    - CHANGES.md
  when: not nrdppath.stat.exists or nrdp_force_reinstall
  tags:
    - nagios-nrdp

- name: nrdp php configuration file
  template:
    src: nrdp/config.inc.php
    dest: /usr/local/nrdp/server/config.inc.php
    mode: 0644
  tags:
    - nagios-nrdp
    - nagios-nrdp-config

- name: nrdp folder perms
  file:
    path: /usr/local/nrdp/
    owner: "{{ nagios.user }}"
    group: "{{ nagios.group }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes
  tags:
    - nagios-nrdp
    - nagios-nrdp-config

- name: nrdp configuration apache file
  template:
    src: nrdp/nrdp.conf
    dest: "{{ nagios_apache.sites_folder }}/nrdp.conf"
    mode: 0644
  notify: restart apache
  tags:
    - nagios-nrdp
