---
- name: Disable ipv6 on all interfaces
  ansible.builtin.sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: "1"
    state: present

- name: Disable ipv6 on default interface
  ansible.builtin.sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: "1"
    state: present
