---

###########
# source: https://www.centlinux.com/2016/09/install-pnp4nagios-nagios-core-centos-7.html
# Grafana Support: https://support.nagios.com/kb/article/nagios-core-using-grafana-with-pnp4nagios-803.html#Grafana_Config

- name: check if pnp4nagios folder exists
  stat:
    path: /usr/local/pnp4nagios
  register: pnp4nagiospath

- name: create temporary directory
  tempfile:
    state: directory
    suffix: pnp4nagios
  register: tempfolder
  changed_when: false
  when: not pnp4nagiospath.stat.exists or pnp4nagios_force_reinstall

- name: creates pnp4nagios
  unarchive:
    src: https://downloads.sourceforge.net/project/pnp4nagios/PNP-0.6/pnp4nagios-0.6.26.tar.gz
    dest: "{{ tempfolder.path }}"
    remote_src: yes
    creates: "{{ tempfolder.path }}/pnp4nagios-0.6.26"
  when: not pnp4nagiospath.stat.exists or pnp4nagios_force_reinstall

- name: makes pnp4nagios
  command: chdir={{ tempfolder.path }}/pnp4nagios-0.6.26 {{ item }}
  with_items:
    - ./configure
    - make all
    - make fullinstall
  args:
    creates: /etc/httpd/conf.d/pnp4nagios.conf
  when: not pnp4nagiospath.stat.exists or pnp4nagios_force_reinstall

- name: Download api.php for grafana integration
  get_url:
    url: https://github.com/lingej/pnp-metrics-api/raw/master/application/controller/api.php
    dest: /usr/local/pnp4nagios/share/application/controllers/api.php
    checksum: sha1:56fd36b2dde0fc6ab618740e8b2f877d0e6065ae
    mode: '0644'

- name: nagios configuration apache file
  template:
    src: pnp4nagios/pnp4nagios.conf
    dest: "{{ apache.sites_folder }}/pnp4nagios.conf"
    mode: 0644
  notify: restart apache

- name: stat install.php pnp4nagios
  stat:
    path: /usr/local/pnp4nagios/share/install.php
  register: pnp4nagios_install_stat

# comment these 3 lines to validate the pnp4nagios installation
- name: rename install.php to install.old
  command: mv /usr/local/pnp4nagios/share/install.php /usr/local/pnp4nagios/share/install.old
  when: pnp4nagios_install_stat.stat.exists

# npcd issues: these commands needs to check after pnp4nagios updates
# https://stackoverflow.com/questions/50077503/npcd-error-executed-command-exits-with-return-code-255:
#   sed -i 's:my \$t1;:my @t1=();\n    my $t1=\\\@t1;:' /usr/local/pnp4nagios/libexec/process_perfdata.pl
- name: issues on process_perfdata.pl file
  replace:
    path: /usr/local/pnp4nagios/libexec/process_perfdata.pl
    regexp: 'my \$t1;'
    replace: 'my @t1=();\n    my $t1=\\@t1;'

# https://github.com/lingej/pnp4nagios/issues/148:
#   sed -i 's:if(sizeof(\$pages:if(is_array(\$pages) \&\& sizeof(\$pages:' /usr/local/pnp4nagios/share/application/models/data.php
- name: issues on data.php file
  replace:
    path: /usr/local/pnp4nagios/share/application/models/data.php
    regexp: 'if\(sizeof\(\$pages'
    replace: 'if(is_array($pages) && sizeof($pages'

# https://forum.checkmk.com/t/services-json-has-a-deprecated-constructor-centos8-fresh-install-with-1-6-0p6/14957/7
#   sed -i 's:function Services_JSON(:function _construct(:' /usr/local/pnp4nagios/share/application/lib/json.php
#   sed -i 's:function Services_JSON_Error(:function _construct(:' /usr/local/pnp4nagios/share/application/lib/json.php
- name: issues on json.php file
  replace:
    path: /usr/local/pnp4nagios/share/application/lib/json.php
    regexp: 'function Services_JSON\('
    replace: 'function _construct('

- name: issues on json.php file
  replace:
    path: /usr/local/pnp4nagios/share/application/lib/json.php
    regexp: 'function Services_JSON_Error\('
    replace: 'function _construct('

- name: issues on Input.php file with php7
  lineinfile:
    path: /usr/local/pnp4nagios/lib/kohana/system/libraries/Input.php
    regexp: '(.*_magic_quotes_.*)'
    state: absent
    backup: yes
  when: ansible_facts.os_family == 'Debian'

- name: pnp4nagios configuration file
  template:
    src: pnp4nagios/npcd.cfg
    dest: /usr/local/pnp4nagios/etc/npcd.cfg
    mode: 0644
  notify: restart npcd
