---
- name: Set postfix to ipv4
  ansible.builtin.replace:
    path: /etc/postfix/main.cf
    regexp: '^inet_protocols = all'
    replace: inet_protocols = ipv4

- name: Start postfix service
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: true
