---
- name: Update dnf cache
  ansible.builtin.dnf:
    autoremove: true
    update_cache: true

- name: Install epel repository
  ansible.builtin.dnf:
    name: oracle-epel-release-el8
    state: present
  when: ansible_facts['distribution'] == 'OracleLinux'

- name: Install postfix package
  ansible.builtin.dnf:
    name:
      - postfix
    state: present

- name: Install apache and openssl packages
  ansible.builtin.dnf:
    name:
      - httpd
      - httpd-tools
      - mod_ssl
      - openssl
      - php-fpm
    state: present

- name: Start php-fpm service
  ansible.builtin.systemd:
    name: php-fpm
    state: started
    enabled: true

- name: Install nagios core packages
  ansible.builtin.dnf:
    name:
      - nagios
    state: present

- name: Install nagios plugins
  ansible.builtin.dnf:
    name: "{{ nrpe_packages }}"
    state: present
    enablerepo: PowerTools

- name: Install essential packages
  ansible.builtin.dnf:
    name: "{{ essential_packages }}"
    state: present

- name: Install rrdtool packages
  ansible.builtin.dnf:
    name: "{{ rrdtool_packages }}"
    state: present
