---
- name: Update dnf cache
  ansible.builtin.dnf:
    autoremove: true
    update_cache: true

- name: Install oracle epel repository
  ansible.builtin.dnf:
    name: "oracle-epel-release-el{{ ansible_facts['distribution_major_version'] }}"
    state: present
  when: ansible_facts['distribution'] == 'OracleLinux'

- name: Import epel gpg key
  ansible.builtin.rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_facts['distribution_major_version'] }}"
    state: present
  when: ansible_facts['distribution'] != 'OracleLinux'

- name: Configure epel repository
  ansible.builtin.yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux $releasever - $basearch
    metalink: "https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch"
    gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever"
    gpgcheck: true
    enabled: true
    state: present
  when: ansible_facts['distribution'] != 'OracleLinux'

- name: Install postfix package
  ansible.builtin.dnf:
    name:
      - postfix
    state: present

- name: Install apache and openssl packages
  ansible.builtin.dnf:
    name:
      - httpd
      - httpd-tools
      - mod_ssl
      - openssl
      - php-fpm
    state: present

- name: Start php-fpm service
  ansible.builtin.systemd:
    name: php-fpm
    state: started
    enabled: true

- name: Install nagios core packages
  ansible.builtin.dnf:
    name:
      - nagios
    state: present

- name: Install nagios plugins
  ansible.builtin.dnf:
    name: "{{ nrpe_packages }}"
    state: present

- name: Install essential packages
  ansible.builtin.dnf:
    name: "{{ essential_packages }}"
    state: present

- name: Install rrdtool packages
  ansible.builtin.dnf:
    name: "{{ rrdtool_packages }}"
    state: present

- name: Create nagios systemd override directory
  ansible.builtin.file:
    path: /etc/systemd/system/nagios.service.d
    state: directory
    mode: "0755"

- name: Ensure nagios service has ExecReload set
  ansible.builtin.copy:
    dest: /etc/systemd/system/nagios.service.d/override.conf
    content: |
      [Service]
      ExecReload=/bin/kill -HUP $MAINPID
    mode: "0644"
  register: __nagioscore_service_override
  notify: Reload systemd daemon
