---
- name: restart apache
  ansible.builtin.service:
    name: "{{ apache.service_name }}"
    state: restarted
    enabled: true

- name: reload nagios
  ansible.builtin.service:
    name: "{{ nagios.service_name }}"
    state: reloaded

- name: restart npcd
  ansible.builtin.systemd_service:
    name: npcd
    state: restarted
    enabled: true
    daemon_reload: true
