---

- name: restart apache
  service:
    name: '{{ apache.service_name }}'
    state: restarted
    enabled: yes

- name: reload nagios
  service:
    name: '{{ nagios.service_name }}'
    state: reloaded

- name: restart npcd
  service:
    name: npcd
    state: restarted
    enabled: yes
