# https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/configmain.html
---
nagios_config_parameters: []
nagios_config_parameters_default:
  accept_passive_host_checks: 1
  accept_passive_service_checks: 1
  additional_freshness_latency: 15
  admin_email: nagios@localhost
  admin_pager: pagenagios@localhost
  allow_empty_hostgroup_assignment: 0
  auto_reschedule_checks: 0
  auto_rescheduling_interval: 30
  auto_rescheduling_window: 180
  bare_update_check: 0
  cached_host_check_horizon: 15
  cached_service_check_horizon: 15
  cfg_dir:
    - "{{ nagios.etc_path }}/hosts"
    - "{{ nagios.etc_path }}/services"
    - "{{ nagios.etc_path }}/assets"
    - "{{ nagios.etc_path }}/templates"
  # cfg_dir:
  #    - "/etc/nagios-plugins/config" #OnlyDebian
  # cfg_file:
  #   - "{{ nagios.etc_path }}/objects/commands.cfg"
  #   - "{{ nagios.etc_path }}/objects/contacts.cfg"
  #   - "{{ nagios.etc_path }}/objects/localhost.cfg"
  #   - "{{ nagios.etc_path }}/objects/templates.cfg"
  #   - "{{ nagios.etc_path }}/objects/timeperiods.cfg"
  check_external_commands: 1
  check_for_orphaned_hosts: 1
  check_for_orphaned_services: 1
  check_for_updates: 1
  check_host_freshness: 0
  check_result_path: "{{ nagios.var_spool_path }}/checkresults"
  check_result_reaper_frequency: 10
  check_service_freshness: 1
  command_file: "{{ nagios.var_spool_path }}/nagios.cmd"
  daemon_dumps_core: 0
  date_format: us
  debug_file: "{{ nagios.var_log_path }}/nagios.debug"
  debug_level: 0
  debug_verbosity: 1
  enable_environment_macros: 0
  enable_event_handlers: 1
  enable_flap_detection: 1
  enable_notifications: 1
  enable_predictive_host_dependency_checks: 1
  enable_predictive_service_dependency_checks: 1
  event_broker_options: -1
  event_handler_timeout: 30
  execute_host_checks: 1
  execute_service_checks: 1
  high_host_flap_threshold: 20.0
  high_service_flap_threshold: 20.0
  host_check_timeout: 30
  host_freshness_check_interval: 60
  host_inter_check_delay_method: s
  illegal_macro_output_chars: ~$&|'"`<>
  illegal_object_name_chars: ~!$%^&*|'"`<>?,()=
  interval_length: 60
  lock_file: "{{ nagios.lock_file }}"
  log_archive_path: "{{ nagios.var_log_path }}/archives"
  log_current_states: 1
  log_event_handlers: 1
  log_external_commands: 1
  log_file: "{{ nagios.var_log_path }}/nagios.log"
  log_host_retries: 1
  log_initial_states: 0
  log_notifications: 1
  log_passive_checks: 1
  log_rotation_method: d
  log_service_retries: 1
  low_host_flap_threshold: 5.0
  low_service_flap_threshold: 5.0
  max_check_result_file_age: 3600
  max_check_result_reaper_time: 30
  max_concurrent_checks: 0
  max_debug_file_size: 1000000
  max_host_check_spread: 30
  max_service_check_spread: 30
  nagios_group: "{{ nagios.group }}"
  nagios_user: "{{ nagios.user }}"
  notification_timeout: 30
  object_cache_file: "{{ nagios.var_spool_path }}/objects.cache"
  obsess_over_hosts: 0
  obsess_over_services: 0
  ochp_timeout: 5
  ocsp_timeout: 5
  passive_host_checks_are_soft: 0
  perfdata_timeout: 5
  precached_object_file: "{{ nagios.var_spool_path }}/objects.precache"
  # process_performance_data: 0
  resource_file: "{{ nagios.etc_path }}/resource.cfg"
  retained_contact_host_attribute_mask: 0
  retained_contact_service_attribute_mask: 0
  retained_host_attribute_mask: 0
  retained_process_host_attribute_mask: 0
  retained_process_service_attribute_mask: 0
  retained_service_attribute_mask: 0
  retain_state_information: 1
  retention_update_interval: 60
  service_check_timeout: 60
  service_check_timeout_state: c
  service_freshness_check_interval: 60
  service_inter_check_delay_method: s
  service_interleave_factor: s
  soft_state_dependencies: 0
  state_retention_file: "{{ nagios.var_spool_path }}/retention.dat"
  status_file: "{{ nagios.var_spool_path }}/status.dat"
  status_update_interval: 10
  temp_file: "{{ nagios.var_spool_path }}/nagios.tmp"
  temp_path: /tmp
  translate_passive_host_checks: 0
  use_aggressive_host_checking: 0
  use_large_installation_tweaks: 0
  use_regexp_matching: 0
  use_retained_program_state: 1
  use_retained_scheduling_info: 1
  use_syslog: 1
  use_true_regexp_matching: 0
  # performance_data
  process_performance_data: 1
  service_perfdata_file: /usr/local/pnp4nagios/var/service-perfdata
  service_perfdata_file_template: DATATYPE::SERVICEPERFDATA\tTIMET::$TIMET$\tHOSTNAME::$HOSTNAME$\tSERVICEDESC::$SERVICEDESC$\tSERVICEPERFDATA::$SERVICEPERFDATA$\tSERVICECHECKCOMMAND::$SERVICECHECKCOMMAND$\tHOSTSTATE::$HOSTSTATE$\tHOSTSTATETYPE::$HOSTSTATETYPE$\tSERVICESTATE::$SERVICESTATE$\tSERVICESTATETYPE::$SERVICESTATETYPE$
  service_perfdata_file_mode: a
  service_perfdata_file_processing_interval: 15
  service_perfdata_file_processing_command: process_service_perfdata_file
  host_perfdata_file: /usr/local/pnp4nagios/var/host-perfdata
  host_perfdata_file_template: DATATYPE::HOSTPERFDATA\tTIMET::$TIMET$\tHOSTNAME::$HOSTNAME$\tHOSTPERFDATA::$HOSTPERFDATA$\tHOSTCHECKCOMMAND::$HOSTCHECKCOMMAND$\tHOSTSTATE::$HOSTSTATE$\tHOSTSTATETYPE::$HOSTSTATETYPE$
  host_perfdata_file_mode: a
  host_perfdata_file_processing_interval: 15
  host_perfdata_file_processing_command: process_host_perfdata_file
  # performance_data
